# Generated by Django 6.0.2 on 2026-02-20 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='About Us', max_length=200)),
                ('subheading', models.CharField(default='A Nonprofit Dedicated to Visual Health and Inclusion', max_length=300)),
                ('body_paragraph_1', models.TextField(blank=True)),
                ('body_paragraph_2', models.TextField(blank=True)),
                ('stat_number', models.CharField(default='100', max_length=20)),
                ('stat_label_line1', models.CharField(default='Percent', max_length=100)),
                ('stat_label_line2', models.CharField(default='Mission', max_length=100)),
                ('stat_label_line3', models.CharField(default='Driven', max_length=100)),
                ('cta_text', models.CharField(default='Read More', max_length=100)),
                ('cta_url', models.CharField(default='/about', max_length=255)),
                ('image_1_url', models.URLField(blank=True)),
                ('image_2_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('founder_vision', 'Founder & Vision'), ('mission', 'Mission'), ('speaking', 'Speaking & Corporate Engagement')], max_length=50, unique=True)),
                ('heading', models.CharField(max_length=200)),
                ('subheading', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True, help_text='Can use HTML')),
                ('body_extra', models.TextField(blank=True)),
                ('image_1_url', models.URLField(blank=True)),
                ('image_2_url', models.URLField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Blog categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CallToActionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Get Involved', max_length=200)),
                ('subheading', models.CharField(default='Support Visual Health and Visual Inclusion', max_length=300)),
                ('body', models.TextField(blank=True)),
                ('primary_button_text', models.CharField(default='Donate', max_length=100)),
                ('primary_button_url', models.CharField(default='/donate', max_length=255)),
                ('secondary_button_text', models.CharField(default='Contact Us', max_length=100)),
                ('secondary_button_url', models.CharField(default='/contact', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FounderPurposeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='About Founder and Purpose', max_length=200)),
                ('subheading', models.CharField(default='The Story Behind Rose Coloured Lens', max_length=300)),
                ('intro_paragraph_1', models.TextField(blank=True)),
                ('intro_paragraph_2', models.TextField(blank=True)),
                ('bullet_1_title', models.CharField(blank=True, max_length=200)),
                ('bullet_1_text', models.TextField(blank=True)),
                ('bullet_2_title', models.CharField(blank=True, max_length=200)),
                ('bullet_2_text', models.TextField(blank=True)),
                ('bullet_3_title', models.CharField(blank=True, max_length=200)),
                ('bullet_3_text', models.TextField(blank=True)),
                ('image_1_url', models.URLField(blank=True)),
                ('image_2_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('cta_text', models.CharField(max_length=100)),
                ('cta_url', models.CharField(default='/about', max_length=255)),
                ('image_url', models.URLField(help_text='Cloudinary image URL')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.SlugField(help_text='e.g. donate, 404, contact, shop', unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('subheading', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Page copies',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, help_text='Cloudinary URL')),
                ('badge', models.CharField(blank=True, help_text='e.g. Bestseller, New', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Rose Coloured Lens (NPC)', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('contact_email', models.EmailField(default='info@rosecoloredlens.org', max_length=254)),
                ('contact_location', models.CharField(default='Johannesburg, South Africa', max_length=200)),
                ('footer_copyright', models.CharField(default='Rose Coloured Lens (NPC), All Rights Reserved.', max_length=200)),
                ('credits_url', models.URLField(blank=True, help_text='e.g. Website by BKG Consulting')),
                ('credits_text', models.CharField(default='Website by BKG Consulting', max_length=200)),
                ('newsletter_heading', models.CharField(default='Newsletter', max_length=200)),
                ('newsletter_description', models.TextField(blank=True, default='Stay informed on visual health, visual inclusion, and advocacy updates.')),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed src URL')),
                ('logo_url', models.URLField(blank=True, help_text='Navbar logo (Cloudinary URL)')),
                ('favicon_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='WhatWeDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_url', models.URLField(blank=True, help_text='Icon image Cloudinary URL')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'What We Do item',
                'verbose_name_plural': 'What We Do items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutSectionBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='main.aboutsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary for cards')),
                ('body', models.TextField(blank=True, help_text='Full content (rich text)')),
                ('featured_image_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='main.blogcategory')),
            ],
            options={
                'ordering': ['-published_at', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSwatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('colour_hex', models.CharField(default='#cccccc', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swatches', to='main.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
