# Generated by Django 5.0.7 on 2026-02-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_aboutpreview_id_alter_aboutsection_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Upload image - will be uploaded to Cloudinary automatically', null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL (auto-filled when image is uploaded)'),
        ),
    ]
