# Generated by Django 5.0.7 on 2026-02-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blogpost_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, default='+27 82 670 9690', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='info@rosecolouredlens.org', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_location',
            field=models.CharField(default='Johannesburg', max_length=200),
        ),
    ]
