# Generated by Django 5.0.7 on 2026-03-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sitesettings_contact_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL slug (e.g., 'egroups', 'pastoral')", unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('header_text', models.TextField(blank=True, help_text='Text displayed in the page header')),
                ('content', models.TextField(blank=True, help_text='Main content text')),
                ('image_url', models.URLField(blank=True, help_text='Main image URL (Cloudinary)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dynamic Page',
                'verbose_name_plural': 'Dynamic Pages',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(default='© 2026 Nairobi Chapel Ngong Hills. All rights reserved.', max_length=200),
        ),
    ]
