# Generated by Django 5.0.7 on 2026-03-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dynamicpage_alter_sitesettings_footer_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicpage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Image alt text for accessibility', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='content_2',
            field=models.TextField(blank=True, help_text='Secondary content (for split template)'),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='cta_text',
            field=models.CharField(blank=True, help_text='Button text', max_length=100),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='cta_text_2',
            field=models.CharField(blank=True, help_text='Secondary button text', max_length=100),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='cta_url',
            field=models.CharField(blank=True, help_text='Button link', max_length=255),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='cta_url_2',
            field=models.CharField(blank=True, help_text='Secondary button link', max_length=255),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='menu_order',
            field=models.PositiveIntegerField(default=0, help_text='Order within the menu'),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='menu_placement',
            field=models.CharField(choices=[('none', 'None - Not in Menu'), ('about', 'About Dropdown'), ('ministries', 'Ministries Dropdown'), ('resources', 'Resources Dropdown'), ('engage', 'Engage Dropdown')], default='none', help_text='Which dropdown menu to appear in', max_length=50),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description'),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (leave empty to use page title)', max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='show_in_menu',
            field=models.BooleanField(default=True, help_text='Show in navigation menu'),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='template',
            field=models.CharField(choices=[('default', 'Default - Image Left, Content Right'), ('full_width', 'Full Width - Hero Image with Overlay'), ('content_only', 'Content Only - No Image'), ('split', 'Split - Two Column Layout'), ('centered', 'Centered - Text Centered with Image Below')], default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='dynamicpage',
            name='content',
            field=models.TextField(blank=True, help_text='Main content text (supports HTML)'),
        ),
    ]
