# Generated by Django 5.0.7 on 2026-03-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_dynamicpage_alt_text_dynamicpage_content_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsectionbullet',
            name='section',
        ),
        migrations.DeleteModel(
            name='AboutSection',
        ),
        migrations.DeleteModel(
            name='AboutSectionBullet',
        ),
    ]
