# Generated by Django 5.0.7 on 2026-03-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_aboutsectionbullet_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='info@ncngonghills.org', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_location',
            field=models.CharField(default='Ngong Hills, Kenya', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, default='+254 797 559118', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='newsletter_description',
            field=models.TextField(blank=True, default='Get updates on our services, events, and community life.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='newsletter_heading',
            field=models.CharField(default='Stay Connected', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Nairobi Chapel Ngong Hills', max_length=200),
        ),
    ]
