# Generated by Django 5.0.7 on 2026-03-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_sitesettings_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary for cards')),
                ('description', models.TextField(blank=True, help_text='Full event description')),
                ('event_date', models.DateTimeField(help_text='Date and time of the event')),
                ('location', models.CharField(blank=True, help_text='Event location', max_length=200)),
                ('image_url', models.URLField(blank=True, help_text='Event image URL (Cloudinary)')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event_date', 'order'],
            },
        ),
    ]
