# Generated by Django 5.0.7 on 2026-03-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
        migrations.DeleteModel(
            name='ProductSwatch',
        ),
    ]
