# Generated by Django 5.0.7 on 2026-03-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_newslettersubscriber_delete_productswatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Service name (e.g., Children's Service)", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of the service')),
                ('day_time', models.CharField(help_text='When the service occurs (e.g., Sundays 11:30 am - 1:00 pm)', max_length=100)),
                ('location', models.CharField(default='Nairobi Chapel Ngong Hills', help_text='Where the service is held', max_length=200)),
                ('place', models.CharField(blank=True, help_text='Specific venue (e.g., Quest Classrooms)', max_length=200)),
                ('image_url', models.URLField(blank=True, help_text='Service image URL (Cloudinary)')),
                ('learn_more_url', models.CharField(blank=True, help_text='Link to more information about this service', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
    ]
