# Generated by Django 6.0.2 on 2026-03-27 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
            ],
            options={
                'verbose_name': 'Page · About',
                'verbose_name_plural': 'Page · About',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.dynamicpage',),
        ),
        migrations.CreateModel(
            name='BibleStudyPage',
            fields=[
            ],
            options={
                'verbose_name': 'Page · Bible study',
                'verbose_name_plural': 'Page · Bible study',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.dynamicpage',),
        ),
        migrations.CreateModel(
            name='ClubFusionPage',
            fields=[
            ],
            options={
                'verbose_name': 'Page · Club Fusion',
                'verbose_name_plural': 'Page · Club Fusion',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.dynamicpage',),
        ),
        migrations.CreateModel(
            name='EgroupsPage',
            fields=[
            ],
            options={
                'verbose_name': 'Page · E-Groups',
                'verbose_name_plural': 'Page · E-Groups',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.dynamicpage',),
        ),
        migrations.CreateModel(
            name='MembershipPage',
            fields=[
            ],
            options={
                'verbose_name': 'Page · Membership',
                'verbose_name_plural': 'Page · Membership',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.dynamicpage',),
        ),
        migrations.CreateModel(
            name='OtherSitePage',
            fields=[
            ],
            options={
                'verbose_name': 'Other site pages',
                'verbose_name_plural': 'Other site pages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.dynamicpage',),
        ),
        migrations.CreateModel(
            name='PastoralCarePage',
            fields=[
            ],
            options={
                'verbose_name': 'Page · Pastoral care',
                'verbose_name_plural': 'Page · Pastoral care',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.dynamicpage',),
        ),
        migrations.CreateModel(
            name='PrayerPage',
            fields=[
            ],
            options={
                'verbose_name': 'Page · Prayer',
                'verbose_name_plural': 'Page · Prayer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.dynamicpage',),
        ),
        migrations.CreateModel(
            name='QuestPage',
            fields=[
            ],
            options={
                'verbose_name': 'Page · Quest',
                'verbose_name_plural': 'Page · Quest',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.dynamicpage',),
        ),
        migrations.CreateModel(
            name='SermonPage',
            fields=[
            ],
            options={
                'verbose_name': 'Page · Sermon',
                'verbose_name_plural': 'Page · Sermon',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.dynamicpage',),
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
            ],
            options={
                'verbose_name': 'Page · Services',
                'verbose_name_plural': 'Page · Services',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.dynamicpage',),
        ),
        migrations.CreateModel(
            name='VolunteerPage',
            fields=[
            ],
            options={
                'verbose_name': 'Page · Volunteer',
                'verbose_name_plural': 'Page · Volunteer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.dynamicpage',),
        ),
    ]
