# Generated by Django 6.0.2 on 2026-03-27 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_proxy_site_pages"),
    ]

    operations = [
        migrations.CreateModel(
            name="PluginPage",
            fields=[],
            options={
                "verbose_name": "Page · Plug-In",
                "verbose_name_plural": "Page · Plug-In",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.dynamicpage",),
        ),
    ]
