# Generated by Django 5.0.7 on 2026-03-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_pagecopy_give_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="watch_online_url",
            field=models.URLField(
                blank=True,
                help_text='YouTube live, premiere, or channel URL (shows "Watch online" on the home page)',
            ),
        ),
    ]
