"""
Django settings for rose_project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cloudinary (read early for INSTALLED_APPS and STORAGES)
CLOUDINARY_CLOUD_NAME = os.environ.get("CLOUDINARY_CLOUD_NAME", "")
CLOUDINARY_API_KEY = os.environ.get("CLOUDINARY_API_KEY", "")
CLOUDINARY_API_SECRET = os.environ.get("CLOUDINARY_API_SECRET", "")
CLOUDINARY_CONFIGURED = bool(
    CLOUDINARY_CLOUD_NAME and CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET
)

# django-ckeditor / ckeditor_uploader — define before INSTALLED_APPS so the setting
# always exists when ckeditor_uploader is imported (avoids ImproperlyConfigured).
CKEDITOR_UPLOAD_PATH = os.environ.get(
    "CKEDITOR_UPLOAD_PATH", "rose-coloured-lens/ckeditor"
)
CKEDITOR_IMAGE_BACKEND = "ckeditor_uploader.backends.PillowBackend"
CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": "full",
        "height": 400,
        "width": "100%",
        "toolbar_Custom": [
            ["Bold", "Italic", "Underline"],
            [
                "NumberedList",
                "BulletedList",
                "-",
                "Outdent",
                "Indent",
                "-",
                "JustifyLeft",
                "JustifyCenter",
                "JustifyRight",
                "JustifyBlock",
            ],
            ["Link", "Unlink"],
            ["RemoveFormat", "Source"],
            ["Image", "Table", "HorizontalRule"],
            ["Styles", "Format", "Font", "FontSize"],
            ["TextColor", "BGColor"],
            ["Maximize"],
        ],
        "toolbar": "Custom",
        "extraPlugins": ",".join(
            [
                "uploadimage",
                "div",
                "autolink",
                "autoembed",
                "embedsemantic",
                "autogrow",
                "widget",
                "lineutils",
                "clipboard",
                "dialog",
                "dialogui",
                "elementspath",
            ]
        ),
    },
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-change-me-in-production")

# DEBUG: read from env; default True for local development.
DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")

# ALLOWED_HOSTS: comma-separated hostnames (override via .env).
_raw_allowed = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").strip()
ALLOWED_HOSTS = [h.strip() for h in _raw_allowed.split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    "jazzmin",  # Must be before django.contrib.admin
    "main.apps.MainConfig",
]
if CLOUDINARY_CONFIGURED:
    # django-cloudinary-storage: before django.contrib.staticfiles per package docs
    INSTALLED_APPS += ["cloudinary_storage", "cloudinary"]
INSTALLED_APPS += [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "ckeditor",
    "ckeditor_uploader",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rose_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.cms_context',
            ],
            'loaders': [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ]),
            ],
        },
    },
]

# Cache configuration for faster page loads
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

WSGI_APPLICATION = 'rose_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise serves collected static files in production (after collectstatic).
WHITENOISE_MAX_AGE = 60 * 60 * 24 * 30

# Media files (user uploads; default storage may be Cloudinary — see STORAGES)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

if CLOUDINARY_CONFIGURED:
    import cloudinary

    cloudinary.config(
        cloud_name=CLOUDINARY_CLOUD_NAME,
        api_key=CLOUDINARY_API_KEY,
        api_secret=CLOUDINARY_API_SECRET,
        secure=True,
    )
    CLOUDINARY_STORAGE = {
        "CLOUD_NAME": CLOUDINARY_CLOUD_NAME,
        "API_KEY": CLOUDINARY_API_KEY,
        "API_SECRET": CLOUDINARY_API_SECRET,
        "SECURE": True,
    }
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        # With django-cloudinary-storage installed, run:
        #   python manage.py collectstatic --noinput --upload-unhashed-files
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    CLOUDINARY_STORAGE = {}
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "location": str(BASE_DIR / "media"),
                "base_url": "/media/",
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# django-cloudinary-storage patches collectstatic and still reads legacy STATICFILES_STORAGE.
STATICFILES_STORAGE = STORAGES["staticfiles"]["BACKEND"]

# Admin dashboard login
LOGIN_URL = "/dashboard/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/dashboard/login/"

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "info@rosecolouredlens.org")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = 'info@rosecolouredlens.org'
SERVER_EMAIL = 'info@rosecolouredlens.org'

# YouTube Data API (sermon page latest videos)
YOUTUBE_API_KEY = os.environ.get("YOUTUBE_API_KEY", "")
YOUTUBE_SERMON_CHANNEL_HANDLE = os.environ.get(
    "YOUTUBE_SERMON_CHANNEL_HANDLE", "ncngonghills"
)
YOUTUBE_FEED_CACHE_SECONDS = int(os.environ.get("YOUTUBE_FEED_CACHE_SECONDS", "900"))

# Jazzmin Admin Theme Configuration
JAZZMIN_SETTINGS = {
    "site_title": "Nairobi Chapel Ngong Hive · Admin",
    "site_header": "Nairobi Chapel Ngong Hive",
    # Shown beside the logo in the sidebar (full name remains in site_header / title).
    "site_brand": "Ngong Hive",
    "site_logo": "admin_branding/ncng-hive-logo.svg",
    "login_logo": "admin_branding/ncng-hive-logo.svg",
    "login_logo_dark": None,
    "site_logo_classes": "",
    "site_icon": "admin_branding/ncng-hive-logo.svg",
    "welcome_sign": "Sign in to manage website content, pages, and media.",
    "copyright": "Nairobi Chapel Ngong Hive",
    # One global navbar search (Jazzmin repeats a full search box per entry if this is a list).
    "search_model": "main.OtherSitePage",
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Admin home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View website", "url": "/", "new_window": True},
    ],
    "usermenu_links": [
        {"name": "View website", "url": "/", "new_window": True},
    ],
    "show_sidebar": True,
    # Flat sidebar: one section per app (headers + links) — easier to scan than nested treeview.
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [
        # Hide auth entries not requested
        "auth.group",
        "auth.user",

        # Hide main entries not requested in your sidebar list
        "main.sitesettings",
        "main.whatwedoitem",
        "main.aboutpreview",
        "main.founderpurposeblock",
        "main.calltoactionblock",
        "main.pastoralteamsection",
        "main.biblestudyresource",
        "main.pagecopy",  # keep ContactPageCopy / GivePageCopy only
        "main.contactsubmission",
        "main.blogcategory",
        "main.blogpost",
        "main.product",
        "main.othersitepage",
        "main.sermonpage",
    ],
    # Sidebar order (exactly as requested)
    "order_with_respect_to": [
        "main.heroslide",            # Hero
        "main.aboutpage",          # Our Story
        "main.service",            # Services
        "main.event",              # Activities
        "main.pastoralcarepage",   # Pastorate
        "main.contactpagecopy",    # Contact
        "main.egroupspage",        # eGroups
        "main.prayerpage",         # Plug-in
        "main.clubfusionpage",    # Club Fusion
        "main.mensministrypage",  # Men's Ministry
        "main.questpage",         # Quest
        "main.womensministrypage",# Women's Ministry
        "main.biblestudypage",    # Bible Study
        "main.membershippage",    # Membership
        "main.volunteerpage",    # Volunteer
        "main.givepagecopy",     # Give
    ],
    # (Kept) Order matches public site: home → ministry pages → blog/shop → utilities → users
    "default_model_order": [
        "SiteSettings",
        "HeroSlide",
        "Service",
        "WhatWeDoItem",
        "AboutPreview",
        "FounderPurposeBlock",
        "CallToActionBlock",
        "Event",
        "AboutPage",
        "PastoralCarePage",
        "PastoralTeamSection",
        "EgroupsPage",
        "PrayerPage",
        "ClubFusionPage",
        "QuestPage",
        "SermonPage",
        "BibleStudyPage",
        "BibleStudyResource",
        "MembershipPage",
        "VolunteerPage",
        "OtherSitePage",
        "BlogCategory",
        "BlogPost",
        "Product",
        "PageCopy",
        "ContactSubmission",
        "User",
    ],
    "custom_links": {},
    "icons": {
        # Auth
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        # Site Settings
        "main.SiteSettings": "fas fa-cog",
        # Homepage
        "main.HeroSlide": "fas fa-images",
        "main.Service": "fas fa-church",
        "main.WhatWeDoItem": "fas fa-hand-holding-heart",
        "main.AboutPreview": "fas fa-info-circle",
        "main.FounderPurposeBlock": "fas fa-user-tie",
        "main.CallToActionBlock": "fas fa-bullhorn",
        "main.Event": "fas fa-calendar-alt",
        "main.AboutPage": "fas fa-info-circle",
        "main.PastoralCarePage": "fas fa-hands-helping",
        "main.PastoralTeamSection": "fas fa-user-friends",
        "main.EgroupsPage": "fas fa-users",
        "main.PrayerPage": "fas fa-plug",
        "main.ClubFusionPage": "fas fa-music",
        "main.QuestPage": "fas fa-compass",
        "main.SermonPage": "fas fa-book-open",
        "main.BibleStudyPage": "fas fa-bible",
        "main.BibleStudyResource": "fas fa-table",
        "main.MembershipPage": "fas fa-id-card",
        "main.VolunteerPage": "fas fa-hands",
        "main.OtherSitePage": "fas fa-file-alt",
        "main.PageCopy": "fas fa-file-alt",
        "main.ContactSubmission": "fas fa-envelope",
        "main.BlogCategory": "fas fa-folder",
        "main.BlogPost": "fas fa-blog",
        "main.Product": "fas fa-shopping-bag",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    # Fix Jazzmin change-form horizontal tabs not opening from URL hash on first load.
    "custom_js": "admin/js/hash_tabs_fix.js",
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    "language_chooser": False,
}